### ISSUE TITLE
Does it work with select option list?

### ISSUE THREAD

**Issue by AshrafFathi** [smucode/react-world-flags#24]
when used with select option its gives [object Object] country in the list instead of flag icon

**Comment by smucode** [comment]
It does not work with regular HTML selects as the values need to be plain strings. I assume you could use something like https://github.com/mledoze/countries, which contains all unicode emoji flags (.code). Last time i checked this approach does not work on linux without installing a new font.

If you just want a country selector with flags there are many libs available for react like:  https://github.com/ekwonye-richard/react-flags-select

If you really want to use this library, you can always use something like https://github.com/jedwatson/react-select which has support for custom rendering.
