### ISSUE TITLE
Very large build size

### ISSUE THREAD

**Issue by adamgajzlerowicz** [smucode/react-world-flags#3]
Thank you for your initiative with this project, although as it is not possible to import a single flag, the final build of my project is increased by 1MB. So.. can't use it in prod 
![screen shot 2018-05-27 at 08 47 00](https://user-images.githubusercontent.com/675615/40583232-8c888bc0-618a-11e8-8246-8fc3f63f3c91.png)

**Comment by smucode** [comment]
Yes, this is a big drawback with the current approach. Not sure the best way to solve this. Since you only require a single flag I suggest you simply use [`svg-country-flags`](https://github.com/hjnilsson/country-flags) directly:

```javascript
import flag from 'svg-country-flags/svg/no.svg'
<img src={flag} />
```

**Comment by dy** [comment]
The best approach would be using separate entries for each flag, as it is done in [@material-ui/icons](https://next.material-ui.com/style/icons/).

`import FranceFlag from 'react-world-flags/fr'`

**Comment by afilp** [comment]
@dy Is this supported here?

**Comment by sljavi** [comment]
+1

**Comment by tomzaku** [comment]
```tsx
import React, { FunctionComponent } from "react";

type LocaleDispatch = {
  updateLocale: (locale: string) => void;
};

type LocaleProps = {
  locale: string;
} & LocaleDispatch;

const Locale: FunctionComponent<LocaleProps> = ({ locale, updateLocale }) => {
  const [flag, setFlag] = React.useState();
  React.useEffect(() => {
    const loadSvg = async () => {
      const countryCode = locale.slice(3).toLowerCase();
      const { default: response } = await import(`svg-country-flags/svg/${countryCode}.svg`);
      setFlag(response);
    };
    loadSvg();
  }, [locale]);
  return <img src={flag} width={40} height={20} onClick={() => updateLocale(locale === "vi-VN" ? "en-US" : "vi-VN")} />;
};
export default Locale;
```
It works for me

**Comment by gcaggia** [comment]
I am grateful for your library @smucode but I had to uninstall it and move to svg images. 
react-world-flag was using ~3MB in my next.js bundle. 
This library is not usable. That's unfortunate.

**Comment by smucode** [comment]
@MCFreddie777 Have a look at v2: https://github.com/smucode/react-world-flags/tree/v2 - it should fix these issues
