### ISSUE TITLE
Flags have different sizes

### ISSUE THREAD

**Issue by cbeltrangomez84** [smucode/react-world-flags#388]
As we can see in a [Flag List](https://www.worldometers.info/geography/flags-of-the-world/), flags have equal sizes, or at least a parameter should indicate if we want all flags to have equal dimensions among each others.

Thanks

**Comment by smucode** [comment]
Hello. Looking at the flag of Nauru https://no.wikipedia.org/wiki/Nauru or the flag of Nepal https://en.wikipedia.org/wiki/Nepal they are not equal size. In the flag list they are actually scaled to fit the given size. Look at how the sun isn't round: 

![image](https://user-images.githubusercontent.com/502358/110085168-13273a80-7d91-11eb-92f8-d20e582fc512.png)

You can specify a width and height `<Flag code="nor" height="16" width="24" />` to make the image the size you want, but whitespace will be added where needed. 

I don't think it makes sense for this lib to change the aspect ratio of flags.
