### ISSUE TITLE
Request: international flag 

### ISSUE THREAD

**Issue by chutchapon** [smucode/react-world-flags#518]
Need international flag.

**Comment by smucode** [comment]
You can pass an optional fallback which renders if the given code doesn't correspond to a flag:

```
<Flag code="foo" fallback={ <img src=... /> } />
```

Is this not sufficient for your usecase?

**Comment by chutchapon** [comment]
> You can pass an optional fallback which renders if the given code doesn't correspond to a flag:
> 
> ```
> <Flag code="foo" fallback={ <img src=... /> } />
> ```
> 
> Is this not sufficient for your usecase?

thank you for your kindness.
