### ISSUE TITLE
Add some flags

### ISSUE THREAD

**Issue by kszinhu** [smucode/react-world-flags#541]
[South America](https://commons.wikimedia.org/wiki/File:Flag_of_South_America_(proposal).svg)
[United Nations](https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Nations.svg)

**Comment by smucode** [comment]
Hi, thanks for the report. This library is limited to any country that has an official ISO 3166-1 country code. And which [svg-country-flags](https://www.npmjs.com/package/svg-country-flags) has a flag for. Sorry about that.
