### ISSUE TITLE
Missing Country flags for the UK

### ISSUE THREAD

**Issue by davecarlson** [smucode/react-world-flags#673]
Sadly, we only have flags for Great Britain/UK.

As the UK is actually 4 countres (Wales, England, Scotland and Northern Ireland), could we also get these flags added ?

**Comment by smucode** [comment]
They should be present. `GB_NIR` etc.

**Comment by davecarlson** [comment]
Ah nice, THANK YOU !

**Comment by Sacro** [comment]
Slight pedantic note, Northern Ireland isn't part of Great Britian, and it also has no seperate offical flag.

**Comment by davecarlson** [comment]
> Slight pedantic note, Northern Ireland isn't part of Great Britian, and it also has no seperate offical flag.
Yup, hence why I wrote that "The UK has..."

For the maintainers of this project, it is "The United Kingdom of Great Britain and Northern Ireland".
So really, the flag for NI should be UK_NIR
