### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by Eusebiotrigo** [smucode/react-world-flags#674]
I'm getting the following error:

```
Type error: 'Flag' cannot be used as a JSX component.
  Its type 'FC<FlagProps>' is not a valid JSX element type.
    Type 'FunctionComponent<FlagProps>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'import("/Users/eusebiotrigo/embley/control-center/node_modules/@types/react-simple-maps/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
```

After the following updates:

| Package | From | To |
| --- | --- | --- |
| [@clerk/nextjs](https://github.com/clerkinc/javascript) | `4.24.1` | `4.25.1` |
| [@tanstack/react-query](https://github.com/TanStack/query/tree/HEAD/packages/react-query) | `4.35.3` | `4.35.7` |
| [@tanstack/react-table](https://github.com/tanstack/table) | `8.10.1` | `8.10.3` |
| [axios](https://github.com/axios/axios) | `1.5.0` | `1.5.1` |
| [flowbite-react](https://github.com/themesberg/flowbite-react) | `0.6.1` | `0.6.3` |
| [next](https://github.com/vercel/next.js) | `13.5.2` | `13.5.3` |
| [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node) | `18.17.19` | `18.18.1` |
| [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react) | `18.2.22` | `18.2.24` |
| [@types/react-simple-maps](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react-simple-maps) | `3.0.0` | `3.0.1` |
| [@types/react-world-flags](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react-world-flags) | `1.4.2` | `1.4.3` |
| [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin) | `6.7.2` | `6.7.3` |
| [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser) | `6.7.2` | `6.7.3` |
| [eslint-config-next](https://github.com/vercel/next.js/tree/HEAD/packages/eslint-config-next) | `13.5.2` | `13.5.3` |
| [postcss](https://github.com/postcss/postcss) | `8.4.30` | `8.4.31` |

**Comment by Eusebiotrigo** [comment]
It works with @types/react 18.2.23.

**Comment by smucode** [comment]
Just bumped the project deps. Let me know if that didn't solve it.

**Comment by Eusebiotrigo** [comment]
Thanks for releasing and updating the dependencies. 
I just tried and sadly, it did not fix the type issue with the Flag component.

**Comment by Eusebiotrigo** [comment]
Ok, this type issue seems to be more with https://www.npmjs.com/package/@types/react-world-flags in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-world-flags than with the library you created.

Thanks!!
