### ISSUE TITLE
Add Chinese Taipei flag

### ISSUE THREAD

**Issue by mar00nie** [smucode/react-world-flags#695]
Could the Chinese Taipei flag be added, for use in sports?

**Comment by mar00nie** [comment]
ISO 3166 code is TPE

**Comment by smucode** [comment]
Hi! this lib uses https://github.com/mledoze/countries and https://github.com/hampusborgos/country-flags for resolving country codes and for the images. Doesn't look like they support Chinese Taipei. I suggest you open an issue there. Once added, I'll happily update this library :)
