### ISSUE TITLE
"svg-country-flags":"^1.2.3"

### ISSUE THREAD

**Issue by danielcai1987** [smucode/react-world-flags#7]
Hi,

Thank you for making react-world-flags!
Would you like to change the package.json line 23 to "svg-country-flags":"^1.2.3"
instead of the git@github.com link? 

Because it would require the developers to have a github account and add SSH key to their account.
Then it can be installed successful through npm/yarn.

Thank you.
DC

**Comment by smucode** [comment]
Sorry about that, fixed now.
